import { useMemo } from 'react'
import Chunk from './Chunk'
import { useWorldStore } from '../store/worldStore'
import { parseChunkKey } from '../engine/world'

/**
 * World
 * ----
 * Mounts one <Chunk> per currently-loaded chunk in the world store's Map. The
 * set of loaded chunks changes dynamically as the player roams (ChunkManager
 * adds/removes entries via worldStore.updateLoadedChunks). When this component
 * re-renders with a new Map, React reconciles the chunk list:
 *   - New keys → mount new <Chunk> (terrain generated by updateLoadedChunks).
 *   - Removed keys → unmount <Chunk> → its useEffect cleanup disposes the
 *     InstancedMesh's geometry/material (prevents GPU memory leaks).
 *   - Existing keys → same <Chunk> (props stable) → no re-render unless that
 *     chunk's own ChunkData changed (handled per-chunk via its store selector).
 */
export default function World() {
  const chunks = useWorldStore((s) => s.chunks)
  // Keys are stable strings ("chunkX,chunkZ"); useMemo avoids re-allocating the
  // array unless the Map reference actually changed.
  const entries = useMemo(() => Array.from(chunks.keys()), [chunks])

  return (
    <>
      {entries.map((key) => {
        const [cx, cz] = parseChunkKey(key)
        return <Chunk key={key} chunkX={cx} chunkZ={cz} />
      })}
    </>
  )
}